### PR TITLE
fix: added failsafe for domain without domainkeys

### LINKED ISSUE #100: Error when trying to Edit a Domain
## Describe the bug
Error 500 when trying to edit an existing Domain

## To Reproduce
1. Go to Domain index
2. Try to edit an existing Domain

## Expected behavior
Should work

## Screenshots
Typed property App\Entity\Domain::$domain_keys must not be accessed before initialization

Image

### PR DESCRIPTION
**Pull request by Rigueur**
## Related issue(s)
https://github.com/Probesys/agentj/issues/100

## How to test manually
-     Go to Domain index
-     Try to edit an existing Domain that doesnt have a domain_keys_id

## Reviewer checklist

- [x] Code is manually tested
- [x] Interface works on both mobiles and big screens
- [x] Interface works on both Firefox and Chrome
- [x] Tests are up to date
- [x] Documentation is up to date
- [x] Pull request has been reviewed and approved

### CODE REVIEW

File: app/src/Controller/DomainController.php [hunk 1]
```diff
@@ -260,8 +260,12 @@ public function edit(Request $request, Domain $domain, FileUploader $fileUploade
...
         }
 
-        $dkim = $this->em->getRepository(DomainKey::class)->find($domain->getDomainKeys()->getId());
-        $dnsInfo = $dkim->getDnsinfo();
+        $dkim = null;
+        $dnsInfo = null;
+        if ($domain->getDomainKeys() !== null) {
+            $dkim = $this->em->getRepository(DomainKey::class)->find($domain->getDomainKeys()->getId());
+            $dnsInfo = $dkim->getDnsinfo();
+        }
```
Comment (marien-probesys) [inline app/src/Controller/DomainController.php]: `$domain->getDomainKeys()` te retourne déjà l’objet `$dkim`, donc il suffit de faire :

```suggestion
        $dkim = $domain->getDomainKeys();
        $dnsInfo = $dkim?->getDnsinfo();
```

(note le `$dkim?->getDnsinfo()` qui retourne `null` si `$dkim` est `null`)

**Review by marien-probesys — DISMISSED** [review]
À part une petite simplification, ça me va :+1:

**Review by ctresvaux — APPROVED** [review]
